- name: create basic directories
  file:
    path: "/home/ubuntu/{{ item }}"
    state: directory
  loop:
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos
